---
# APP
- hosts: "{{symfony_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - when: ["cops_symfony_lifecycle_app|default(true)"]
    tags: ["cops_symfony_lifecycle_app"]
    block:
    - include_role: {name: symfony_vars, allow_duplicates: false}
    - include_role: {name: symfony,      allow_duplicates: false}
