---
cops_django_name: djangoinstance
cops_django_project_module_name: "{{cops_django_name}}"
cops_django_settings_module: "{{cops_django_project_module_name}}.settings.instances.{{cops_django_deploy_env}}"
cops_django_py_ver: "3.7"
cops_django_deploy_env: "dev"
cops_django_docker_image_tag: "{{cops_django_name}}"
cops_django_default_docker_tag: "latest"
cops_django_docker_tag: "{{cops_django_default_docker_tag}}"
cops_django_tld_domain: example.com
cops_django_mail_domain: "{{ cops_django_tld_domain }}"
cops_django_default_gitref: "master"
cops_django_gitref: "{{cops_django_default_gitref}}"
cops_django_dir: "/srv/docker/{{cops_django_name}}"
cops_django_hostname: "{{cops_django_deploy_env}}-{{cops_django_name}}.{{cops_django_tld_domain}}"
cops_django_alternate_hostnames: [".{{cops_django_tld_domain}}"]
cops_django_secret_key: "SuperSecret"
cops_django_gateway: "{{ ansible_default_ipv4.address}}"
cops_django_composename: "{{cops_django_name}}"
cops_django_db_host: "db"
cops_django_db_port: "5432"
cops_django_db_user: "secretJFCxwPHz99R9jIi"
cops_django_db_password: "secret4gzQNe3c8851VOJ"
cops_django_db_name: "{{cops_django_name}}"
cops_django_devmode: False
cops_django_build_args: "--no-cache django cron"
# backup could be remove in a-while when we have redeployed it everywhere
cops_django_restarted_services_default: "db redis django nginx backup cron"
cops_django_restarted_services: "{{cops_django_restarted_services_default}}"
cops_django_purge_volumes: [statics]
cops_django_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_django_build: false
cops_django_pull: true
cops_django_registries: []
#- {registry: registry.foo.net, username: foo, password: bar}
cops_django_compose_files: [docker-compose.yml, docker-compose-prod.yml]
cops_django_dc:
  docker-compose {% for i in cops_django_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_django_composename}}"
cops_django_default_from_email: noreply@{{cops_django_hostname}}
cops_django_server_email: "{{cops_django_default_from_email}}"
cops_django_mailcatcher_user: mailcatcher
cops_django_mailcatcher_password: mailcatcher
cops_django_server_email: "{{cops_django_default_from_email}}"
cops_django_email_server: mailcatcher
cops_django_email_host_user: ''
cops_django_email_host_password: ''
cops_django_email_host_port: 1025
cops_django_email_use_tls: 'no'
cops_django_http_protect_user: "root"
cops_django_http_protect_password: "rootroot"
cops_django_redis_url: "redis://redis:6379/1"
cops_django_hosts_whitelist: "{{(
    [cops_django_hostname, '0.0.0.0', '.{0}'.format(cops_django_hostname)]+
    cops_django_alternate_hostnames
  )|join('-|_')}}"
cops_django_sentry_tags: ["env:{{cops_django_deploy_env}}"]
cops_django_sentry_dsn: ''
cops_django_docker_env_freeform: |-
  {{ cops_django_docker_env_defaults}}
  {{ cops_django_docker_env_extra}}
cops_django_docker_env_defaults: |-
  # This need to be changed in production
  SECRET_KEY={{ cops_django_secret_key }}
  # db
  POSTGRES_HOST={{ cops_django_db_host }}
  POSTGRES_PORT={{ cops_django_db_port }}
  POSTGRES_USER={{ cops_django_db_user }}
  POSTGRES_DB={{ cops_django_db_name }}
  POSTGRES_PASSWORD={{cops_django_db_password }}
  PGPASSWD={{cops_django_db_password }}
  # cors
  DJANGO__CORS_ORIGIN_WHITELIST={{cops_django_hosts_whitelist}}
  DJANGO__ALLOWED_HOSTS={{cops_django_hosts_whitelist}}
  DJANGO__DEPLOY_ENV={{cops_django_deploy_env}}
  DJANGO__HTTP_PROTECT_USER={{cops_django_http_protect_user}}
  DJANGO__HTTP_PROTECT_PASSWORD={{cops_django_http_protect_password}}
  {% if cops_django_sentry_dsn %}
  DJANGO__SENTRY_DSN={{cops_django_sentry_dsn}}
  DJANGO__SENTRY_RELEASE={{cops_django_docker_tag}}
  DJANGO__SENTRY_TAGS={{cops_django_sentry_tags|join(',')}}
  {% endif %}
  {% if cops_django_devmode %}
  DJANGO__CORS_ORIGIN_ALLOW_ALL=y
  DJANGO__DEBUG=y
  {% endif %}
  DJANGO__DEFAULT_FROM_EMAIL={{ cops_django_default_from_email }}
  DJANGO__SERVER_EMAIL={{ cops_django_server_email }}
  DJANGO__EMAIL_HOST={{cops_django_email_server}}
  DJANGO__EMAIL_PORT={{cops_django_email_host_port}}
  DJANGO__EMAIL_HOST_USER={{cops_django_email_host_user}}
  DJANGO__EMAIL_HOST_PASSWORD={{cops_django_email_host_password}}
  MAILCATCHER_USER={{cops_django_mailcatcher_user}}
  MAILCATCHER_PASSWORD={{cops_django_mailcatcher_password}}
  REDIS_URL={{cops_django_redis_url}}
# free form for params inside dockerenv
cops_django_dotenv: |-
  APP_TYPE=django
  DJANGO_SETTINGS_MODULE={{cops_django_settings_module}}
  DJANGO_PY_VER={{ cops_django_py_ver }}
  DJANGO_NAME={{ cops_django_name }}
  COMPOSE_PROJECT_NAME={{cops_django_composename}}
  CI_COMMIT_SHA={{cops_django_gitref}}
  DJANGO_IMAGE={{ cops_django_docker_image }}
  DJANGO_IMAGE_VERSION={{cops_django_docker_tag}}
cops_django_dotenv_extra: ""
# free form for params inside dockerenv
cops_django_docker_env_extra: ""
# free form for params inside local.py
cops_django_localpy_extra: ""
# Normally playbook is in ./.ansible/playbooks
cops_django_code_dir: "{{playbook_dir}}/../.."
cops_django_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", ".git",
    "--exclude", ".tox",
    "--exclude", ".env",
    "--exclude", "docker.env"]
