---
cops_symfony_name: symfonyinstance
cops_symfony_project_module_name: "{{cops_symfony_name}}"
cops_symfony_settings_module: "{{cops_symfony_project_module_name}}.settings.instances.{{cops_symfony_deploy_env}}"
cops_symfony_php_ver: "7.2"
cops_symfony_deploy_env: "dev"
cops_symfony_docker_image_tag: "{{cops_symfony_name}}"
cops_symfony_default_docker_tag: "latest"
cops_symfony_docker_tag: "{{cops_symfony_default_docker_tag}}"
cops_symfony_tld_domain: example.com
cops_symfony_mail_domain: "{{ cops_symfony_tld_domain }}"
cops_symfony_default_gitref: "master"
cops_symfony_gitref: "{{cops_symfony_default_gitref}}"
cops_symfony_dir: "/srv/docker/{{cops_symfony_name}}"
cops_symfony_hostname: "{{cops_symfony_deploy_env}}-{{cops_symfony_name}}.{{cops_symfony_tld_domain}}"
cops_symfony_alternate_hostnames: [".{{cops_symfony_tld_domain}}"]
cops_symfony_secret_key: "SuperSecret"
cops_symfony_gateway: "{{ ansible_default_ipv4.address}}"
cops_symfony_composename: "{{cops_symfony_name}}"
cops_symfony_db_user: "secretJFCxdffffwPH9R9jIi"
cops_symfony_db_password: "secrdet44ff4gzQNe3c885ttgJ"
cops_symfony_db_name: "{{cops_symfony_name}}"
cops_symfony_devmode: False
cops_symfony_build_args: "--no-cache symfony cron"
# backup could be remove in a-while when we have redeployed it everywhere
cops_symfony_restarted_services_default: "db redis symfony nginx backup cron"
cops_symfony_restarted_services: "{{cops_symfony_restarted_services_default}}"
cops_symfony_purge_volumes: [statics]
cops_symfony_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_symfony_build: false
cops_symfony_pull: true
cops_symfony_registries: []
#- {registry: registry.foo.net, username: foo, password: bar}
cops_symfony_compose_files: [docker-compose.yml, docker-compose-prod.yml]
cops_symfony_dc:
  docker-compose {% for i in cops_symfony_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_symfony_composename}}"
cops_symfony_default_from_email: noreply@{{cops_symfony_hostname}}
cops_symfony_server_email: "{{cops_symfony_default_from_email}}"
cops_symfony_mailcatcher_user: mailcatcher
cops_symfony_mailcatcher_password: mailcatcher
cops_symfony_server_email: "{{cops_symfony_default_from_email}}"
cops_symfony_email_server: mailcatcher
cops_symfony_email_host_user: ''
cops_symfony_email_host_password: ''
cops_symfony_email_host_port: 1025
cops_symfony_email_use_tls: 'no'
cops_symfony_hosts_whitelist: "{{(
    [cops_symfony_hostname, '0.0.0.0', '.{0}'.format(cops_symfony_hostname)]+
    cops_symfony_alternate_hostnames
  )|join('-|_')}}"
cops_symfony_sentry_tags: ["env:{{cops_symfony_deploy_env}}"]
cops_symfony_sentry_dsn: ''
cops_symfony_docker_env_freeform: |-
  {{ cops_symfony_docker_env_defaults}}
  {{ cops_symfony_docker_env_extra}}
cops_symfony_docker_env_defaults: |-
  # This need to be changed in production
  SECRET_KEY={{ cops_symfony_secret_key }}
  # db
  POSTGRES_USER={{ cops_symfony_db_user }}
  POSTGRES_DB={{ cops_symfony_db_name }}
  POSTGRES_PASSWORD={{cops_symfony_db_password }}
  PGPASSWD={{cops_symfony_db_password }}
  # cors
  SYMFONY__CORS_ORIGIN_WHITELIST={{cops_symfony_hosts_whitelist}}
  SYMFONY__ALLOWED_HOSTS={{cops_symfony_hosts_whitelist}}
  SYMFONY__DEPLOY_ENV={{cops_symfony_deploy_env}}
  {% if cops_symfony_sentry_dsn %}
  SYMFONY__SENTRY_DSN={{cops_symfony_sentry_dsn}}
  SYMFONY__SENTRY_RELEASE={{cops_symfony_docker_tag}}
  SYMFONY__SENTRY_TAGS={{cops_symfony_sentry_tags|join(',')}}
  {% endif %}
  {% if cops_symfony_devmode %}
  SYMFONY__CORS_ORIGIN_ALLOW_ALL=y
  SYMFONY__DEBUG=y
  {% endif %}
  SYMFONY__DEFAULT_FROM_EMAIL={{ cops_symfony_default_from_email }}
  SYMFONY__SERVER_EMAIL={{ cops_symfony_server_email }}
  SYMFONY__EMAIL_HOST={{cops_symfony_email_server}}
  SYMFONY__EMAIL_PORT={{cops_symfony_email_host_port}}
  SYMFONY__EMAIL_HOST_USER={{cops_symfony_email_host_user}}
  SYMFONY__EMAIL_HOST_PASSWORD={{cops_symfony_email_host_password}}
  MAILCATCHER_USER={{cops_symfony_mailcatcher_user}}
  MAILCATCHER_PASSWORD={{cops_symfony_mailcatcher_password}}
# free form for params inside dockerenv
cops_symfony_dotenv: |-
  APP_TYPE=symfony
  SYMFONY_SETTINGS_MODULE={{cops_symfony_settings_module}}
  SYMFONY_PHP_VER={{ cops_symfony_php_ver }}
  SYMFONY_NAME={{ cops_symfony_name }}
  COMPOSE_PROJECT_NAME={{cops_symfony_composename}}
  CI_COMMIT_SHA={{cops_symfony_gitref}}
  SYMFONY_IMAGE={{ cops_symfony_docker_image }}
  SYMFONY_IMAGE_VERSION={{cops_symfony_docker_tag}}
cops_symfony_dotenv_extra: ""
# free form for params inside dockerenv
cops_symfony_docker_env_extra: ""
# Normally playbook is in ./.ansible/playbooks
cops_symfony_code_dir: "{{playbook_dir}}/../.."
cops_symfony_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", ".git",
    "--exclude", ".tox",
    "--exclude", ".env",
    "--exclude", "docker.env"]
